import { type RouteConfig, index, layout, route } from '@react-router/dev/routes'

export default [
  index('routes/home.tsx'),
  route('sign-in', 'routes/sign-in.tsx'),
  route('sign-in/verify-2fa', 'routes/sign-in.verify-2fa.tsx'),
  route('sign-up', 'routes/sign-up.tsx'),
  route('forgot-password', 'routes/forgot-password.tsx'),
  route('reset-password', 'routes/reset-password.tsx'),
  route('account-deleted', 'routes/account-deleted.tsx'),
  route('api/auth/*', 'routes/api.auth.$.ts'),
  route('api/ai', 'routes/api.ai.ts'),
  route('api/inngest', 'routes/api.inngest.ts'),
  route('api/organizations', 'routes/api.organizations.ts'),
  route('api/social/connect', 'routes/api.social.connect.ts'),
  route('api/webhooks', 'routes/api.webhooks.ts'),
  route('api/api-keys', 'routes/api.api-keys.ts'),
  route('api/v1/posts', 'routes/api.v1.posts.ts'),
  route('api/v1/users/me', 'routes/api.v1.users.me.ts'),
  route('api/v1/auth/verify', 'routes/api.v1.auth.verify.ts'),
  route('api/v1/zapier/posts/recent', 'routes/api.v1.zapier.posts.recent.ts'),
  route('api/v1/zapier/exports/recent', 'routes/api.v1.zapier.exports.recent.ts'),
  layout('routes/dashboard/layout.tsx', [
    route('dashboard', 'routes/dashboard/index.tsx'),
    route('dashboard/canvas', 'routes/dashboard/canvas.tsx'),
    route('dashboard/video', 'routes/dashboard/video.tsx'),
    route('dashboard/social', 'routes/dashboard/social.tsx'),
    route('dashboard/crawler', 'routes/dashboard/crawler.tsx'),
    route('dashboard/ai', 'routes/dashboard/ai.tsx'),
    route('dashboard/webhooks', 'routes/dashboard/webhooks.tsx'),
    route('dashboard/api-keys', 'routes/dashboard/api-keys.tsx'),
    route('dashboard/plugins', 'routes/dashboard/plugins.tsx'),
    route('dashboard/organizations', 'routes/dashboard/organizations.tsx'),
    route('dashboard/organizations/:orgId', 'routes/dashboard/organizations.$orgId.tsx'),
    route('dashboard/settings/security', 'routes/dashboard/settings.security.tsx'),
    route('dashboard/settings/password', 'routes/dashboard/settings.password.tsx'),
    route('dashboard/settings/sessions', 'routes/dashboard/settings.sessions.tsx'),
    route('dashboard/settings/account', 'routes/dashboard/settings.account.tsx'),
    route('admin/users', 'routes/admin/users.tsx'),
    route('admin/users/:userId', 'routes/admin/users.$userId.tsx'),
  ]),
] satisfies RouteConfig
